image: node:20

definitions:
  steps:
    - step: &build-extension
        name: Build Chrome Extension
        caches:
          - node
        script:
          - apt-get update && apt-get install -y zip
          - export GIT_COMMIT=$(git rev-parse --short HEAD)
          - export GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          - export BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          - export VERSION=$(node -p "require('./manifest.json').version")
          - |
            cat > build-info.json << EOF
            {
              "version": "${VERSION}",
              "git_commit": "${GIT_COMMIT}",
              "git_commit_full": "$(git rev-parse HEAD)",
              "git_branch": "${GIT_BRANCH}",
              "git_tag": "$(git describe --tags --always)",
              "build_date": "${BUILD_DATE}",
              "build_number": "${BITBUCKET_BUILD_NUMBER}",
              "bitbucket_repo": "${BITBUCKET_REPO_FULL_NAME}",
              "bitbucket_commit_url": "https://bitbucket.org/${BITBUCKET_REPO_FULL_NAME}/commits/${BITBUCKET_COMMIT}",
              "github_docs": "https://github.com/Apra-Labs/ai-code-buddy",
              "github_pages": "https://apra-labs.github.io/ai-code-buddy/"
            }
            EOF
          - cat build-info.json
          - mkdir -p build
          - cp -r icons build/
          - cp background.js content.js manifest.json popup-multi.html popup-multi.js build-info.json build/
          - cd build
          - zip -r "../ai-code-buddy-v${VERSION}-${GIT_COMMIT}.zip" .
          - cd ..
          - cp "ai-code-buddy-v${VERSION}-${GIT_COMMIT}.zip" "ai-code-buddy-v${VERSION}.zip"
          - ls -lh ai-code-buddy-*.zip
          - unzip -l "ai-code-buddy-v${VERSION}.zip" | head -20
          - echo "Verifying build-info.json in package"
          - unzip -p "ai-code-buddy-v${VERSION}.zip" build-info.json
          - echo "Uploading to Bitbucket Downloads for easy access..."
          - echo "Repository ${BITBUCKET_REPO_FULL_NAME}"
          - |
            if [ -n "${BITBUCKET_REPO_FULL_NAME}" ]; then
              curl -v -X POST "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_FULL_NAME}/downloads" \
                -u "${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}" \
                -F "files=@ai-code-buddy-v${VERSION}-${GIT_COMMIT}.zip" 2>&1 | tail -20
            else
              echo "BITBUCKET_REPO_FULL_NAME not set, skipping upload"
            fi
        artifacts:
          - ai-code-buddy-v${VERSION}-${GIT_COMMIT}.zip
          - build-info.json

    - step: &validate-extension
        name: Validate Extension
        caches:
          - node
        script:
          - cd icons && npm install && cd ..
          - echo "Running image validator..."
          - cd test && node image-validator.js || true
          - echo "Running link validator..."
          - timeout 60 node link-validator.js || true

    - step: &create-git-tag
        name: Create Git Tag
        script:
          - export VERSION=$(node -p "require('./manifest.json').version")
          - export GIT_COMMIT=$(git rev-parse --short HEAD)
          - |
            if git rev-parse "v${VERSION}" >/dev/null 2>&1; then
              echo "Tag v${VERSION} already exists, skipping tag creation"
            else
              echo "Creating tag v${VERSION} for commit ${GIT_COMMIT}"
              git tag -a "v${VERSION}" -m "Release v${VERSION} - Chrome Web Store submission"
              git push origin "v${VERSION}"
              echo "Tag v${VERSION} created and pushed"
            fi

pipelines:
  default:
    - step: *build-extension
    - step: *validate-extension

  branches:
    main:
      - step: *build-extension
      - step: *validate-extension
      - step: *create-git-tag

  tags:
    'v*':
      - step:
          <<: *build-extension
          name: Build Release for Chrome Web Store
      - step:
          <<: *validate-extension
          name: Validate Release Build
      - step:
          name: Chrome Web Store Submission Ready
          script:
            - export VERSION=$(node -p "require('./manifest.json').version")
            - export GIT_COMMIT=$(git rev-parse --short HEAD)
            - export GIT_TAG=$(git describe --tags --exact-match)
            - echo "============================================"
            - echo "   CHROME WEB STORE SUBMISSION READY"
            - echo "============================================"
            - echo "Version: ${VERSION}"
            - echo "Git Tag: ${GIT_TAG}"
            - echo "Commit Hash: ${GIT_COMMIT}"
            - echo "Download from: https://bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads/"
            - echo "Filename: ai-code-buddy-v${VERSION}-${GIT_COMMIT}.zip"
            - echo "Next steps:"
            - echo "1. Download the ZIP from the link above"
            - echo "2. Go to Chrome Web Store Developer Console"
            - echo "3. Upload the ZIP file"
            - echo "4. Update VERSION.json with store URL after publication"
            - echo "============================================"

  custom:
    # Manual trigger for building without tagging
    build-only:
      - step: *build-extension

    # Manual trigger for validation only
    validate-only:
      - step: *validate-extension
